// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import process from 'node:process';
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // ใช้ DIRECT_URL สำหรับ migrations; fallback เป็น DATABASE_URL เมื่อ environment ยังไม่ตั้ง DIRECT_URL
    url: (process.env['DIRECT_URL'] || process.env['DATABASE_URL']) as string,
  },
});
